### ISSUE TITLE
ERROR  Failure while reading configuration file 'config.yaml'

### ISSUE THREAD

**Issue by TBR-BRD** [twam/fritzbox2mqtt#7]
Hello i have a error message:

Python v 3.9

python3 fritzbox2mqtt.py -c config.yaml

2024-04-25 10:40:57,187 [MainThread     ] ERROR  Failure while reading configuration file 'config.yaml': ScannerError('while parsing a tag', <yaml.error.Mark object at 0x7fbde02e20>, "expected URI, but found '\\n'", <yaml.error.Mark object at 0x7fbde02eb0>)

Please help me

**Comment by twam** [comment]
Can you post a copy of your `config.yaml`? (With removed passwords)

**Comment by TBR-BRD** [comment]
yes, thank you

```
mqtt:
  address: al.myfritz.net
  port: 2268
#  ssl: 1
  username: t
  password: !
  prefix: fritzbox/home

fritzbox:
  address: fritz.box
  defaultPeriod: 5
  port: 49000
  username: fb
  password: !

  services:
    DeviceInfo:
      prefix: deviceInfo
      actions:
        GetInfo:
          period: 3600
          values:
            NewDeviceLog:
              topic: DeviceLog
              type: str
            NewManufacturerName:
              topic: ManufacturerName
              type: str
            NewManufacturerOUI:
              topic: ManufacturerOUI
              type: str
            NewModelName:
              topic: ModelName
              type: str
            NewDescription:
              topic: Description
              type: str
            NewProductClass:
              topic: ProductClass
              type: str
            NewSerialNumber:
              topic: SerialNumber
              type: str
            NewSoftwareVersion:
              topic: SoftwareVersion
              type: str
            NewHardwareVersion:
              topic: HardwareVersion
              type: str
            NewSpecVersion:
              topic: SprecVersion
              type: str
            NewProvisioningCode:
              topic: ProvisioningCode
              type: str
            NewUpTime:
              topic: Uptime
              type: str
    WANCommonInterfaceConfig:
      prefix: wan
      period: 60
      actions:
        GetTotalBytesSent:
          values:
            NewTotalBytesSent:
              topic: totalBytesSent
              type: int
        GetTotalBytesReceived:
          values:
            NewTotalBytesReceived:
              topic: totalBytesReceived
              type: int
    WLANConfiguration:[1-2,3]:
      prefix: wifi{id}
      actions:
        GetTotalAssociations:
          period: 300
          values:
            NewTotalAssociations:
              topic: totalAssociations
              type: int
        GetSecurityKeys:
          period: 600
          values:
            NewWEPKey0:
              topic: WEPKey0
              type: str
            NewWEPKey1:
              topic: WEPKey1
              type: str
            NewWEPKey2:
              topic: WEPKey2
              type: str
            NewWEPKey3:
              topic: WEPKey3
              type: str
            NewPreSharedKey:
              topic: preSharedKey
              type: str
            NewKeyPassphrase:
              topic: passphrase
              type: str
        GetInfo:
          period: 600
          values:
            NewEnable:
              topic: enable
              type: int
            NewStatus:
              topic: status
              type: str
            NewMaxBitRate:
              topic: maxBitRate
              type: str
            NewChannel:
              topic: channel
              type: str
            NewSSID:
              topic: ssid
              type: str
            NewBeaconType:
              topic: beaconType
              type: str
            NewMACAddressControlEnabled:
              topic: MACAddressControlEnabled
              type: int
            NewStandard:
              topic: standard
              type: str
            NewBSSID:
              topic: bssid
              type: str
            NewBasicEncryptionModes:
              topic: encryptionMode
              type: str
            NewBasicAuthenticationMode:
              topic: authenticationMode
              type: str
            NewMaxCharsSSID:
              topic: MaxCharsSSID
              type: int
            NewMinCharsSSID:
              topic: MinCharsSSID
              type: int
            NewAllowedCharsSSID:
              topic: AllowedCharsSSID
              type: str
            NewMaxCharsPSK:
              topic: MaxCharsPSK
              type: int
            NewMinCharsPSK:
              topic: MinCharsPSK
              type: int
            NewAllowedCharsPSK:
              topic: AllowedCharsPSK
              type: str
```
